<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .topic {
            font-size: 35px !important;
            margin: 10px;
            /* text-decoration:underline; */

        }

        p{
            font-size: 20px;
            font-family: "Times New Roman", Times, serif;
            align: left;
            margin-left: 290px;
        }
        .pic{
            width: 700px;
            height:450px;

            margin-top:80px;
        }
       .wise-topic{
        font-size: 22px !important;
  
       }
       iframe{
           margin:30px;
       }
    
    </style>
</head>

<body>
    <?php include 'beginner.php' ?>
    <p><b class="topic">How to Analyze any company</b><br><br>
    <b class="wise-topic">What Are The Key Qualitative Factors To Look For In A Company?</b><br><br>
Qualitative factors are part of a company’s ethos and an integral part of their DNA. These qualitative factors could be attributed to some basic vision of the company; some corporate principles adhered to, a responsive team, ability to foresee change etc. Here are some key qualitative aspects that can impact company valuations.
<br><br>
🟢 How effectively the company is adapting its business model to changes in tastes and preferences in the market? Is the company really ahead of the curve on this aspect?<br>
🟢 How the industry is getting disrupted and how the company is adapting to these changes? Is the company able to build advantages around these disruptions?<br>
🟢 Can the business continue its leadership position in the medium to long term and how is the company preparing for the future?<br>
🟢 How is the company tapping the future opportunities in the business, how is it sprucing execution skills and how it is adapting its product lines.<br>
🟢 How does the market rate the quality of the management and what is the succession plan in place at the top?<br>
🟢 Do customers look at the products of the company as a high-value or low value product and what is the company doing about this perception?<br>
🟢 How is the company taking care of its distributors, wholesalers, vendors and other channel partners?<br>
🟢 How is the organization structure of the company? Is it bulky or is it lean and mean? Is the organization structure in sync with the future plans of the company?<br>
🟢 What is the company’s strategy to manage risk of the business and does the top management get involved in business risk reduction?<br>
🟢 Does the company follow high standards of corporate governance in terms of disclosure, transparency and putting the interests of stakeholders on top?
<br><br>
<br>
This is a sample list but it will surely give an idea of how to go about evaluating the all-important qualitative aspects of the business.
<br><br>
<b class="wise-topic">Quantitative Aspects - How to Read the Income Statement</b><br><br>
Income statement of a company or the P/L account is a consolidated periodic statement showing revenues, costs and profitability of a firm for any given period. Financial results are published each quarter by companies while audited financials are published annually. As part of the listing agreement, companies are required to file these financial statements with the stock exchange. Here are some of the important components of the P&L account.
<br><br>
 
<br>
Net Sales: refers to the revenues generated by the company from its core business of selling goods and services. Net sales are always presented net of GST costs.
<br><br>
Direct Costs: can be directly attributed to business. These include costs like raw material, factory wages, electrical costs, fuel costs etc. Lower the direct costs, higher the operating efficiency of the firm.
<br><br>
EBITDA: The Earnings before Interest, Tax, Depreciation and Amortization is the difference between Net Sales and Direct Costs. EBIDTA is a measure of the operating efficiency of the company and enables comparison of companies irrespective of capital structure.
<br><br>
Depreciation/ Amortization: is provided as a non-cash charge so that the tax shields on this depreciation can be used to create a reserve for the replenishment of machinery and equipment at a future date. When depreciation is deducted from EBITDA you get EBIT (Earnings before interest and tax)
<br><br>
Interest: is the cost of loans, bonds and other borrowings taken by the business. An increase in the interest cost is attributed to an increase or decrease in the debt outstanding or in the cost of funds. When interest is deducted from EBIT, you get PBT.
<br><br>
Profit before Tax (PBT): refers to the total profit of the company for the period after meeting all the expenses. It is the profit on which the company is liable to pay taxes to the government.
<br><br>
Profit after Tax (PAT): is the bottom line or the profit that the company finally makes after payout all costs. The company decides what part of this profit should be paid out as dividends and how much should be ploughed back into the business.
<br><br>
 

The income statement is a flow and measures how much profit was made during the period (one quarter or one full year). The income statement also presents the Basic EPS and the Fully Diluted EPS (after considering all potential dilutions of capital in the future). Income statement is important from an analytical point of view as it captures in a nutshell whether the business is profitable at an operational level or not.
<br>
    <a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiL6bPnsNT1AhWqxDgGHSlcAbcQFnoECBwQAQ&url=https%3A%2F%2Fwww.mdpi.com%2F2071-1050%2F11%2F18%2F4838%2Fpdf&usg=AOvVaw3KtB9XsQ9YRkAFep6M_Wxp">Dawnload complete pdf</a>
</p>

<div>
<iframe width="560" height="315" src="https://www.youtube.com/embed/POfmy7ZQAb4?start=95" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
</body>

</html>